### ISSUE TITLE
Read from Capture give nothing

### ISSUE THREAD

**Issue by ugjka** [mesilliac/pulse-simple#4]
Read: `0 <nil>`

**Comment by ugjka** [comment]
ok so the data is read, but it reports 0 bytes read which breaks io.Reader
you can use Read directly and ignore the n

**Comment by mesilliac** [comment]
It seems the pulse-simple API itself does not return the number of bytes read, in stead returning 0 on success and -1 on failure.

As this output is redundant with the error value, i'll modify the wrapper so that it returns the full number of bytes read/written on success, and 0 bytes read/written on failure. This should ensure basic compatibility with io.Reader and io.Writer. Sadly the information about how much was read/written in the case of failure simply isn't made available.

For consistency i'll remove the integer return value from Drain() and Flush(), which is also redundant with the error value.

**Comment by mesilliac** [comment]
This commit should fix the issue. Thanks for reporting it :)
